<?php

namespace DoctrineProxies\__CG__\Chamilo\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Chamilo\UserBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'userId', 'username', 'usernameCanonical', 'emailCanonical', 'email', 'locked', 'enabled', 'expired', 'credentialsExpired', 'credentialsExpireAt', 'expiresAt', 'lastname', 'firstname', 'password', 'phone', 'address', 'imageFile', 'salt', 'lastLogin', 'createdAt', 'updatedAt', 'confirmationToken', 'passwordRequestedAt', 'courses', 'classes', 'dropBoxReceivedFiles', 'dropBoxSentFiles', 'roles', 'profileCompleted', 'groups', 'curriculumItems', 'portals', 'sessionAsGeneralCoach', 'extraFields', 'resourceNodes', 'sessionCourseSubscriptions', 'achievedSkills', 'commentedUserSkills', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'authSource', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'status', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'officialCode', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'pictureUri', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'creatorId', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'competences', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'diplomas', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'openarea', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'teach', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'productions', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'language', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'registrationDate', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'expirationDate', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'active', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'openid', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'theme', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'hrDeptId'];
        }

        return ['__isInitialized__', 'id', 'userId', 'username', 'usernameCanonical', 'emailCanonical', 'email', 'locked', 'enabled', 'expired', 'credentialsExpired', 'credentialsExpireAt', 'expiresAt', 'lastname', 'firstname', 'password', 'phone', 'address', 'imageFile', 'salt', 'lastLogin', 'createdAt', 'updatedAt', 'confirmationToken', 'passwordRequestedAt', 'courses', 'classes', 'dropBoxReceivedFiles', 'dropBoxSentFiles', 'roles', 'profileCompleted', 'groups', 'curriculumItems', 'portals', 'sessionAsGeneralCoach', 'extraFields', 'resourceNodes', 'sessionCourseSubscriptions', 'achievedSkills', 'commentedUserSkills', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'authSource', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'status', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'officialCode', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'pictureUri', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'creatorId', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'competences', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'diplomas', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'openarea', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'teach', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'productions', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'language', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'registrationDate', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'expirationDate', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'active', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'openid', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'theme', '' . "\0" . 'Chamilo\\UserBundle\\Entity\\User' . "\0" . 'hrDeptId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function postPersist(\Doctrine\ORM\Event\LifecycleEventArgs $args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postPersist', [$args]);

        return parent::postPersist($args);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$userId]);

        return parent::setId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEncoderName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncoderName', []);

        return parent::getEncoderName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDropBoxSentFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDropBoxSentFiles', []);

        return parent::getDropBoxSentFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getDropBoxReceivedFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDropBoxReceivedFiles', []);

        return parent::getDropBoxReceivedFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setDropBoxSentFiles($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDropBoxSentFiles', [$value]);

        return parent::setDropBoxSentFiles($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setDropBoxReceivedFiles($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDropBoxReceivedFiles', [$value]);

        return parent::setDropBoxReceivedFiles($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setCourses($courses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourses', [$courses]);

        return parent::setCourses($courses);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourses', []);

        return parent::getCourses();
    }

    /**
     * {@inheritDoc}
     */
    public function isEqualTo(\FOS\UserBundle\Model\UserInterface $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEqualTo', [$user]);

        return parent::isEqualTo($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortals', []);

        return parent::getPortals();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortal($portal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortal', [$portal]);

        return parent::setPortal($portal);
    }

    /**
     * {@inheritDoc}
     */
    public function setPortals($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortals', [$value]);

        return parent::setPortals($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurriculumItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurriculumItems', []);

        return parent::getCurriculumItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurriculumItems($items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurriculumItems', [$items]);

        return parent::setCurriculumItems($items);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasses($classes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasses', [$classes]);

        return parent::setClasses($classes);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasses', []);

        return parent::getClasses();
    }

    /**
     * {@inheritDoc}
     */
    public function getLps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLps', []);

        return parent::getLps();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleteNameWithUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleteNameWithUsername', []);

        return parent::getCompleteNameWithUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleteName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleteName', []);

        return parent::getCompleteName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleteNameWithClasses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleteNameWithClasses', []);

        return parent::getCompleteNameWithClasses();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthSource($authSource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthSource', [$authSource]);

        return parent::setAuthSource($authSource);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthSource', []);

        return parent::getAuthSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfficialCode($officialCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfficialCode', [$officialCode]);

        return parent::setOfficialCode($officialCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfficialCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfficialCode', []);

        return parent::getOfficialCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPictureUri($pictureUri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPictureUri', [$pictureUri]);

        return parent::setPictureUri($pictureUri);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictureUri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictureUri', []);

        return parent::getPictureUri();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatorId($creatorId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatorId', [$creatorId]);

        return parent::setCreatorId($creatorId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatorId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatorId', []);

        return parent::getCreatorId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompetences($competences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompetences', [$competences]);

        return parent::setCompetences($competences);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompetences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompetences', []);

        return parent::getCompetences();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiplomas($diplomas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiplomas', [$diplomas]);

        return parent::setDiplomas($diplomas);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiplomas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiplomas', []);

        return parent::getDiplomas();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenarea($openarea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenarea', [$openarea]);

        return parent::setOpenarea($openarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenarea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenarea', []);

        return parent::getOpenarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeach($teach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeach', [$teach]);

        return parent::setTeach($teach);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeach', []);

        return parent::getTeach();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductions($productions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductions', [$productions]);

        return parent::setProductions($productions);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductions', []);

        return parent::getProductions();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationDate($registrationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationDate', [$registrationDate]);

        return parent::setRegistrationDate($registrationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationDate', []);

        return parent::getRegistrationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpirationDate($expirationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpirationDate', [$expirationDate]);

        return parent::setExpirationDate($expirationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpirationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpirationDate', []);

        return parent::getExpirationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenid($openid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenid', [$openid]);

        return parent::setOpenid($openid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpenid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpenid', []);

        return parent::getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTheme($theme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTheme', [$theme]);

        return parent::setTheme($theme);
    }

    /**
     * {@inheritDoc}
     */
    public function getTheme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTheme', []);

        return parent::getTheme();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrDeptId($hrDeptId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrDeptId', [$hrDeptId]);

        return parent::setHrDeptId($hrDeptId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrDeptId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrDeptId', []);

        return parent::getHrDeptId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', []);

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberSince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberSince', []);

        return parent::getMemberSince();
    }

    /**
     * {@inheritDoc}
     */
    public function isOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOnline', []);

        return parent::isOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', []);

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $lastLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', [$lastLogin]);

        return parent::setLastLogin($lastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', []);

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraFields', []);

        return parent::getExtraFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraFieldList($extraFields)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraFieldList', [$extraFields]);

        return parent::setExtraFieldList($extraFields);
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraFields($extraFields)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraFields', [$extraFields]);

        return parent::setExtraFields($extraFields);
    }

    /**
     * {@inheritDoc}
     */
    public function addExtraFields(\Chamilo\CoreBundle\Entity\ExtraFieldValues $extraFieldValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtraFields', [$extraFieldValue]);

        return parent::addExtraFields($extraFieldValue);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtraField(\Chamilo\CoreBundle\Entity\ExtraFieldValues $attribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtraField', [$attribute]);

        return parent::removeExtraField($attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function hasExtraFieldByName($attributeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasExtraFieldByName', [$attributeName]);

        return parent::hasExtraFieldByName($attributeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraFieldByName($attributeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraFieldByName', [$attributeName]);

        return parent::getExtraFieldByName($attributeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessionCourseSubscriptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionCourseSubscriptions', []);

        return parent::getSessionCourseSubscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessionCourseSubscriptions($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessionCourseSubscriptions', [$value]);

        return parent::setSessionCourseSubscriptions($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', []);

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', [$confirmationToken]);

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', []);

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', [$ttl]);

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiresAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiresAt', []);

        return parent::getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCredentialsExpireAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredentialsExpireAt', []);

        return parent::getCredentialsExpireAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', [$date]);

        return parent::setCredentialsExpireAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setGroups($groups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroups', [$groups]);

        return parent::setGroups($groups);
    }

    /**
     * {@inheritDoc}
     */
    public function setTwoStepVerificationCode($twoStepVerificationCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwoStepVerificationCode', [$twoStepVerificationCode]);

        return parent::setTwoStepVerificationCode($twoStepVerificationCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwoStepVerificationCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwoStepVerificationCode', []);

        return parent::getTwoStepVerificationCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiography($biography)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiography', [$biography]);

        return parent::setBiography($biography);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiography()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiography', []);

        return parent::getBiography();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfBirth($dateOfBirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfBirth', [$dateOfBirth]);

        return parent::setDateOfBirth($dateOfBirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfBirth', []);

        return parent::getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookData($facebookData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookData', [$facebookData]);

        return parent::setFacebookData($facebookData);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookData', []);

        return parent::getFacebookData();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookName($facebookName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookName', [$facebookName]);

        return parent::setFacebookName($facebookName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookName', []);

        return parent::getFacebookName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookUid($facebookUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookUid', [$facebookUid]);

        return parent::setFacebookUid($facebookUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookUid', []);

        return parent::getFacebookUid();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGplusData($gplusData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGplusData', [$gplusData]);

        return parent::setGplusData($gplusData);
    }

    /**
     * {@inheritDoc}
     */
    public function getGplusData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGplusData', []);

        return parent::getGplusData();
    }

    /**
     * {@inheritDoc}
     */
    public function setGplusName($gplusName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGplusName', [$gplusName]);

        return parent::setGplusName($gplusName);
    }

    /**
     * {@inheritDoc}
     */
    public function getGplusName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGplusName', []);

        return parent::getGplusName();
    }

    /**
     * {@inheritDoc}
     */
    public function setGplusUid($gplusUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGplusUid', [$gplusUid]);

        return parent::setGplusUid($gplusUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getGplusUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGplusUid', []);

        return parent::getGplusUid();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', [$locale]);

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', []);

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimezone($timezone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimezone', [$timezone]);

        return parent::setTimezone($timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimezone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimezone', []);

        return parent::getTimezone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterData($twitterData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterData', [$twitterData]);

        return parent::setTwitterData($twitterData);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterData', []);

        return parent::getTwitterData();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterName($twitterName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterName', [$twitterName]);

        return parent::setTwitterName($twitterName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterName', []);

        return parent::getTwitterName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterUid($twitterUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterUid', [$twitterUid]);

        return parent::setTwitterUid($twitterUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterUid', []);

        return parent::getTwitterUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullname', []);

        return parent::getFullname();
    }

    /**
     * {@inheritDoc}
     */
    public function getRealRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealRoles', []);

        return parent::getRealRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRealRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRealRoles', [$roles]);

        return parent::setRealRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', []);

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', []);

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', []);

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', [$role]);

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', []);

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', []);

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', []);

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsExpired', []);

        return parent::isCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', []);

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocked', []);

        return parent::isLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', []);

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function isUser(\FOS\UserBundle\Model\UserInterface $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUser', [$user]);

        return parent::isUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$role]);

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', [$usernameCanonical]);

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', [$boolean]);

        return parent::setCredentialsExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', [$emailCanonical]);

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$boolean]);

        return parent::setEnabled($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', [$boolean]);

        return parent::setExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', [$date]);

        return parent::setExpiresAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', [$boolean]);

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', [$password]);

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', [$boolean]);

        return parent::setLocked($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', [$date]);

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', []);

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', []);

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', [$name]);

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', [$group]);

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', [$group]);

        return parent::removeGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$role]);

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function getAchievedSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAchievedSkills', []);

        return parent::getAchievedSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function setAchievedSkills($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAchievedSkills', [$value]);

        return parent::setAchievedSkills($value);
    }

    /**
     * {@inheritDoc}
     */
    public function hasSkill(\Chamilo\CoreBundle\Entity\Skill $skill)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasSkill', [$skill]);

        return parent::hasSkill($skill);
    }

    /**
     * {@inheritDoc}
     */
    public function isProfileCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isProfileCompleted', []);

        return parent::isProfileCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileCompleted($profileCompleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileCompleted', [$profileCompleted]);

        return parent::setProfileCompleted($profileCompleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessionAsGeneralCoach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionAsGeneralCoach', []);

        return parent::getSessionAsGeneralCoach();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessionAsGeneralCoach($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessionAsGeneralCoach', [$value]);

        return parent::setSessionAsGeneralCoach($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentedUserSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentedUserSkills', []);

        return parent::getCommentedUserSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentedUserSkills($commentedUserSkills)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentedUserSkills', [$commentedUserSkills]);

        return parent::setCommentedUserSkills($commentedUserSkills);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictureLegacy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictureLegacy', []);

        return parent::getPictureLegacy();
    }

}
